# Generated by Django 5.0.2 on 2024-03-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_membership_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='membership',
            new_name='Offers',
        ),
    ]
