# Generated by Django 5.0.2 on 2024-03-26 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_membership_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='animals/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offers',
            name='number',
            field=models.IntegerField(max_length=4),
        ),
    ]
