# Generated by Django 5.0.2 on 2024-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_offers_images_alter_offers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='number',
            field=models.IntegerField(),
        ),
    ]
