# Generated by Django 5.0.2 on 2024-04-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='adult',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='first',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='kids',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=True, max_length=254, null=True),
        ),
    ]
