# Generated by Django 5.0.4 on 2024-04-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_customer_name_customer_address_customer_adult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='payment',
            new_name='price',
        ),
    ]
