# Generated by Django 5.0.4 on 2024-04-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_payment_offers_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='images',
            new_name='image',
        ),
    ]
