# Generated by Django 6.0.5 on 2026-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiporder',
            old_name='card',
            new_name='offer',
        ),
        migrations.RemoveField(
            model_name='membershiporder',
            name='user',
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='user_email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='user_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
